### ISSUE TITLE
TerminusX subdocument property editor for description field can't be used 

### ISSUE THREAD

**Issue by hoijnet** [terminusdb/terminusx#1]
**Describe the bug**
Adding text to the description of a property (String or Numeric) in TerminusX fails. Error 400 is returned from the server (reported in browser console).

**To Reproduce**
1. Go to Data Product Model view
2. Select a subdocument type
3. Go to properties tab
4. Add property or edit existing property of type string or numeric
5. Add id name, and random string to description field (example: "test")
6. Click on floppy icon/save
4. See error "Failed to update schema graph"

**Expected behavior**
The added description to the property of the subdocument should be saved into the schema graph for the subdocument.

**Screenshots**
![image](https://user-images.githubusercontent.com/144317/136649582-c1152f93-e660-4ae0-bd8a-0f7bc06c4dd8.png)

**Info (please complete the following information):**
 - OS: macOS/Microsoft Edge (Chromium-based) browser
 - TerminusX console

**Additional context**
N/A

**Comment by spl** [comment]
This is now working on TerminusX. Thanks for the report!
