### ISSUE TITLE
Missing image on Team Invite 

### ISSUE THREAD

**Issue by OJ423** [terminusdb/terminusx#13]
Noticed a missing image on the team's invite in TerminusX. It links to the Kooba test site.
It should link to: https://terminusdb.com/img/placeholders/teams.svg

![image](https://user-images.githubusercontent.com/88653154/161959303-4c0c85d4-6a3b-4bcc-8fa6-b3f94679ffb4.png)

**Comment by spl** [comment]
Fixed by @Francesca-Bit!
