### ISSUE TITLE
TerminusX document editor does not allow changes in subdocument

### ISSUE THREAD

**Issue by GavinMendelGleason** [terminusdb/terminusx#20]
Try to edit the Nuclear data product and change the location or capacity.

![Screenshot from 2022-04-25 15-07-27](https://user-images.githubusercontent.com/1993386/165095418-7daa4bc5-880c-4fc1-9de2-996a776f9f13.png)

**Comment by KittyJose** [comment]
isnt capacity and location key fields of document class - Quantity and Geo Coordinates according to the schema?
Thats why you cant edit?
